USB_VID = 0xDEAD
USB_PID = 0xBEEF

USB_PRODUCT = "ESP32S3 0.42 OLED"
USB_MANUFACTURER = "01Space"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 4MB

CIRCUITPY_I2C_ALLOW_INTERNAL_PULL_UP = 1
# CIRCUITPY_REQUIRE_I2C_PULLUPS = 0

CIRCUITPY_ESPCAMERA = 0
